### ISSUE TITLE
English translations

### ISSUE THREAD

**Issue by brianveltman** [dkuk/auto_fields#1]
I will add the english translations next week.

**Comment by dkuk** [comment]
Not important.  Plugin does not works on RM higher than 2.0.3. I think that it will no be any progress on this plugin. At least we have no plans on it in next two month. It uses a lot of prototype code. Now we are working on global issue management plugin which will include fexible configurable buttons for fast issue change, dynamic workflow graphs (on admin pages), auto fields settings and many other features which may be useful in corporate. Unfortunately, looks like it will not be public :(

**Comment by alterdaemon** [comment]
Hi,
you have made a great work there, I haven't found anything close to that and I really need auto setting values based on the issue statuses

sorry to hear that this plugin won't be supported anymore but hey..
what about this 'global issue management plugin'? I would gladly pay for something like this :)

**Comment by dkuk** [comment]
Hi,
I'll ask about commercial. We have no decision about price yet :)  Also we are planning live demo, but it is in progress now, because of inner corporate needs priority. We have a couple plugins for integration RM into bussiness. Our corporate plugin for issue managament called 'luxury buttons'. Don't realy shure that it is a stright you are searching for.
Basic idea of managament - is a     tunable buttons which is clear for simple users. Every button will be shown depending on display conditions of each button. Also button actions can automaticaly change fields, display fields, restrict avalilable values in select boxes. It extends builtin workflows with draggable customized scheme, which shown number of buttons for each status and number of buttons on state-to-state transitions. It helps to setup realy huge projects. 
So it behaviour looks like auto_fields but with a flexible actions depending on roles, projects, issue state, user-to-issue relations etc.
If button not requires any data be inputed (set only some status and othe fields), the action will be fast, other way it will display restricted form. Any changes which logged, can be undoed by special button, which roll backs changes for issue.
Also plugin integrates functionality of tracker-project-role permissions for new issues.
Sorry for skin and russian interface, but I have no time now.
Some screens
![screen1](https://f.cloud.github.com/assets/1817515/672136/d897d028-d870-11e2-87b6-97aacc399ffa.png)
![screen2](https://f.cloud.github.com/assets/1817515/672137/d910b3a8-d870-11e2-9bc5-f753a5549017.png)
![screen3](https://f.cloud.github.com/assets/1817515/672138/d961caf4-d870-11e2-9cd4-fee0f4f970e8.png)

It works for RM 2.0.3+

**Comment by alterdaemon** [comment]
looks nice and promises great flexibility, good luck with (also commercial?) deployment :)

**Comment by dkuk** [comment]
We've started :) and glad to offer you our buttons plugin for $29.
http://rmplus.pro/en
Complex demo with other plugins is also available.
